#!/usr/bin/env bash
# Merge the per-agent literature files into the shared views:
#   literature/search-logs/*.md   -> literature/search-log.md
#   literature/bib/*.bib          -> literature/references.bib   (duplicate DOIs / keys dropped)
#   literature/to-acquire.d/*.md  -> literature/to-acquire.md
# Safe to run any time; the merged files are regenerated from scratch.
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
import pathlib, re

lit = pathlib.Path("literature")

def table_rows(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        if re.match(r"^\|[\s\-|:]+\|$", s):          # separator row
            continue
        if s.lower().startswith(("| date", "| bibkey")):  # header row
            continue
        rows.append(s)
    return rows

def agent_files(folder, ext):
    return sorted(p for p in (lit / folder).glob(f"*{ext}") if not p.name.startswith("_") and p.name != "README.md")

# --- search log ---
rows = []
for f in agent_files("search-logs", ".md"):
    rows += table_rows(f)
rows.sort(key=lambda r: r.split("|")[1].strip())  # by date
out = ["# Search Log (merged — generated by scripts/merge-literature.sh, do not edit)", "",
       f"Total searches: {len(rows)}", "",
       "| # | Date | Agent | Database | Query string | Filters | Hits | Screened | Included | Notes |",
       "|---|------|-------|----------|--------------|---------|------|----------|----------|-------|"]
out += [f"| {i} {r}" for i, r in enumerate(rows, 1)]
(lit / "search-log.md").write_text("\n".join(out) + "\n", encoding="utf-8")
n_searches = len(rows)

# --- bibtex ---
entries, seen_doi, seen_key, dups = [], set(), set(), []
for f in agent_files("bib", ".bib"):
    text = f.read_text(encoding="utf-8")
    for m in re.finditer(r"@\w+\s*\{\s*([^,\s]+)\s*,.*?\n\}", text, re.S):
        entry, key = m.group(0), m.group(1).strip()
        doi_m = re.search(r"doi\s*=\s*[{\"]([^}\"]+)", entry, re.I)
        doi = doi_m.group(1).strip().lower() if doi_m else None
        if key in seen_key or (doi and doi in seen_doi):
            dups.append(f"{key} ({f.name})")
            continue
        seen_key.add(key)
        if doi:
            seen_doi.add(doi)
        entries.append(entry)
header = "% Generated by scripts/merge-literature.sh from literature/bib/*.bib — do not edit by hand.\n\n"
(lit / "references.bib").write_text(header + "\n\n".join(entries) + "\n", encoding="utf-8")

# --- to acquire ---
rows = []
for f in agent_files("to-acquire.d", ".md"):
    rows += [f"| ☐ | {f.stem} {r}" for r in table_rows(f)]
out = ["# PDFs to acquire via FH library (merged — generated, do not edit)", "",
       "Download via FH Kufstein library access and save as `literature/pdfs/<bibkey>.pdf`.", "",
       "| ☐ | Requested by | bibkey | Title | DOI | Why it matters |",
       "|---|--------------|--------|-------|-----|----------------|"] + rows
(lit / "to-acquire.md").write_text("\n".join(out) + "\n", encoding="utf-8")

print(f"search-log.md:   {n_searches} searches")
print(f"references.bib:  {len(entries)} entries" + (f", {len(dups)} duplicates skipped: {', '.join(dups)}" if dups else ""))
print(f"to-acquire.md:   {len(rows)} PDFs to download")
PY
